inherit_from: "./vggt_long/configs/base_config.yaml"

Weights:
  model: 'G3T'
  G3T: null  # this will be set from inside
  DBoW: './vggt_long/weights/ORBvoc.txt'
  SALAD: './vggt_long/weights/dino_salad.ckpt'
  DNIO: './vggt_long/weights/dinov2_vitb14_pretrain.pth'

Model:
  chunk_size: 25
  overlap: 7
  loop_chunk_size: 3
  loop_enable: False  # True  # setting to False to disable loop closure for now
  useDBoW: False
  delete_temp_files: True
  align_method: 'numba' # 'numba' or 'numpy', use 'numba' would be faster

  calib: False
  h: null
  w: null
